### PR TITLE
add locale, python3 support, usage and standard dates

### PR DESCRIPTION
**Pull request by anarcat**
copy of https://github.com/dangersalad/emacs.d/pull/1, made before i found out about this repo, which should be linked from http://hledger.org/manual.html#timelog

### CODE REVIEW

**Comment by anarcat** [comment]
@jwiegley would you prefer this be split into multiple PRs? note that it will probably conflict with #3 but the merge should be fairly trivial.

**Comment by anarcat** [comment]
actually, i was able to merge this in my "deploy" branch so presumably this is fine.

**Comment by jwiegley** [comment]
Hi @anarcat, I'm afraid this version breaks my use case.  I haven't looked into it, since I only need it to do the one thing that I use it for.  If you'd like me to assign ownership of this repository over to you, just delete your fork and I'll give public development over to you.  I'll keep my own copy private.

**Comment by anarcat** [comment]
hmm... what exactly breaks your use case here?

i'd prefer to collaborate, and make sure you can still use the project in your use case, because it will certainly manifest itself for other people! even if i take on maintainership (which I don't mind doing), i'd still need to respond to needs like yours.

it would be great if you could spend the extra time (which i know is rare) to explain exactly how i could fix this for you.

then i'd be happy to either redo a PR for you, fork off, or whatever...

**Comment by jwiegley** [comment]
Ok, @anarcat, I'll see today if I can get it working with your changes, and if
not I'll report back my findings. Thanks for being a willing supporter. Let's
transfer ownership of this repository to you whenever you're ready.

**Comment by jwiegley** [comment]
Ah, I see you added `-s` and `-e` options, good.

**Comment by anarcat** [comment]
i *did* try to make this work ;)

i'm ready to get access whenever you want, but i don't know if you want to completely give up ownership... to be honest, there isn't that much more stuff i would put in there ;)

if anything, what i'd like to do would be to merge this in org-mode or something else so that i don't have to carry the script around everywhere I go in a git repository (and instead have it shipped with a debian package, neatly available in my $PATH ;)...

**Comment by jwiegley** [comment]
If you're willing to respond to future user issues, then I'm happy for you to own the repository.

**Comment by jwiegley** [comment]
But yes, inclusion into org-mode itself, especially since the timeclock format is actually defined by Emacs' `timeclock.el`, would be ideal.

**Comment by jwiegley** [comment]
Btw, for me to transfer ownership, `anarcat/org2tc` cannot already exist.

**Comment by anarcat** [comment]
okay. i've removed the anarcat/org2tc repository.

do you have any suggestions on the bureaucratic process i should follow to merge this elsewhere? PR on org-mode? on emacs itself? bug report?

**Pull request merged**
